### ISSUE TITLE
Use of rewrap outside of comments (particularly in plain text or markdown files)

### ISSUE THREAD

**Issue by orospakr** [stkb/vscode-rewrap#1]
Emacs M-q worked in most situations, including outside of comments (but if used in a comment, it would honour the comment block and expand the comment syntax onto the new lines, etc.)

Thanks :)

**Comment by stkb** [comment]
Thanks for the request. Yeah I'm planning to add support for wrapping regular text, in markdown and other plain text files. Are there other sorts of files you'd need this in?

**Comment by stkb** [comment]
I've added this feature in [v0.3.0](https://github.com/stkb/vscode-rewrap/releases/tag/v0.3.0). At the moment the paragraph detection is a bit crude; it does all text between blank lines. But you can always select lines to wrap yourself if it doesn't give the desired result. Let me know if you have any problems with it!

**Comment by orospakr** [comment]
Amazing! Thank you, I'll give it a try :)
