### ISSUE TITLE
Don't wrap long URLs

### ISSUE THREAD

**Issue by ithinkihaveacat** [stkb/vscode-rewrap#10]
Rewrap hard wraps strings at the `rewrap.wrappingColumn`, which can break URLs if they are longer than `rewrap.wrappingColumn`.

![screen shot 2016-09-06 at 11 33 32 am](https://cloud.githubusercontent.com/assets/51244/18270627/d1076842-7425-11e6-893d-f2c3363e8984.png)

![screen shot 2016-09-06 at 11 33 43 am](https://cloud.githubusercontent.com/assets/51244/18270630/d599b4b4-7425-11e6-8a8e-499d63b69d62.png)

**Comment by stkb** [comment]
Fair request; I'll try to fix this soon

**Comment by stkb** [comment]
@ithinkihaveacat  Sorry this took a while. It's been implemented in the latest version (v0.6.2). Let me know if anything's not working as expected.

**Comment by ithinkihaveacat** [comment]
Didn't take long at all! Thanks so much.
