### ISSUE TITLE
Rewrap started failing?

### ISSUE THREAD

**Issue by peterbourgon** [stkb/vscode-rewrap#11]
Mac OS El Capitan 10.11.4, VS Code Version 1.5.2 (1.5.2), Rewrap 0.6.0

![screen shot 2016-09-19 at 14 57 01](https://cloud.githubusercontent.com/assets/114509/18632779/6a768186-7e79-11e6-96d0-fdbdc9f1a673.png)

**Comment by peterbourgon** [comment]
I closed some tabs and opened some other tabs, and it started working again. I'll leave the issue open in case you want to debug further...

**Comment by stkb** [comment]
Thanks for reporting. Unfortunately I can't really tell anything from that; it's all just vscode's own code. I'll leave this open for a while in case you or anyone else has the same problem and we can work on reproducing it, and I'll add some more logging code into the next version to try to diagnose any errors that occur.

**Comment by nicot** [comment]
Hi @stkb, I think I'm running into this issue. I'm on VS Code 1.6.1 (rolled back from 1.7), macOS Sierra 10.12.1, and rewrap 0.6.2

Here's the log:
```
[Extension Host] TypeError: Cannot read property '0' of null
    at Object.textAfterPrefix (/Users/nico/.vscode/extensions/stkb.rewrap-0.6.2/out/src/Strings.js:28:51)
    at /Users/nico/.vscode/extensions/stkb.rewrap-0.6.2/out/src/Section.js:35:33
    at Array.map (native)
    at new Section (/Users/nico/.vscode/extensions/stkb.rewrap-0.6.2/out/src/Section.js:32:18)
    at BasicLanguage.findSections (/Users/nico/.vscode/extensions/stkb.rewrap-0.6.2/out/src/BasicLanguage.js:35:38)
    at wrapSomething (/Users/nico/.vscode/extensions/stkb.rewrap-0.6.2/out/src/Main.js:33:28)
    at /Users/nico/.vscode/extensions/stkb.rewrap-0.6.2/out/src/Main.js:15:20
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:13:23492
    at e.edit (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:12:16971)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:13:23458
```

I can only reproduce it in one file right now, a compiled version of https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/goToDeclaration/common/goToDeclaration.ts.

Thanks for the great plugin.

**Comment by stkb** [comment]
@nicot Thanks, that helps a lot, but I'm having trouble reproducing. Could you upload the exact file that it errors on (you can attach a file to a comment here), and tell me which comment in it you're trying to wrap?

**Comment by nicot** [comment]
Here's a gist with the failing code/line: https://gist.github.com/nicot/aed1b230392ec2a3bcdc7b2ac970f653#file-gotodeclaration-js-L321. It blows up on every line I've tried in that file though.

**Comment by stkb** [comment]
Perfect! thanks. In that file, it's the empty `//` on line 54 with nothing after it, that's causing the error. I'll get on to fixing it.

**Comment by stkb** [comment]
Have just published v0.6.3 which hopefully fixes the issue (have tried on vscode 1.6.1 and 1.7.1). Could you update and confirm?

**Comment by nicot** [comment]
Works perfectly now! Thanks a bunch for the fix and the awesome plugin.

**Comment by stkb** [comment]
Great! Thanks for the help
