### ISSUE TITLE
Sentence ending

### ISSUE THREAD

**Issue by tschijnmo** [stkb/vscode-rewrap#17]
In the Vim `gq` operator and the Emacs `fill-paragraph` command, when we have something like,

```
A long sentence on a line, longer than the width, ending on the line with a period.
Another sentence on the next line.
```

it will be refilled into something like

```
A long sentence on a line, longer than the width, ending on the line with 
a period.  Another sentence on the next line.
```

with two spaces after the period.  This is also the convention recommended by some coding standards like PEP8.  vscode-rewrap has awesome features.  If an option can be added for the handling of sentence ending, it could be really great!

**Comment by stkb** [comment]
Hi @tschijnmo, thanks for the request. I never knew those wrappers did that and I'll be happy to implement the feature in the next version.

I might have to come back to you if I have questions about how to deal with edge cases.

**Comment by tschijnmo** [comment]
@stkb Thank you for willing to add this feature.  This could mean a lot for the maintenance of some code bases with consistency requirement on this.  If there is anything you need help, I would be very willing to do it and submit a PR.

**Comment by stkb** [comment]
@tschijnmo I have a preview version for you to test. First you can download this file: [rewrap-0.7.0.zip](https://github.com/stkb/vscode-rewrap/files/598085/rewrap-0.7.0.zip)
Then you need to change the extension of the file `rewrap-0.7.0.zip` to `rewrap-0.7.0.vsix`.

Then you can install it in vscode. To do that go to the extensions sidebar, then the "..." in the top right and "Install from VSIX...". Choose the .vsix file and it will overwrite the current version of rewrap you have.

#### A few notes:

The feature isn't enabled by default. To enable it, you have to add `"rewrap.doubleSentenceSpacing": true` to your settings.json.

Secondly, it works with lines ending in `.`, `?` or `!` (tested these in Vim). I don't know if I missed any other characters)

Thirdly, rewrap already has a feature that if a line ends in two (or more) spaces, a line break will be inserted after it. This new feature doesn't change that. So you have to make sure that you don't already add two spaces after the `.` at the end of the line (one is ok)

eg (* represents a space)
```
This wraps.
With this.

This wraps.**With this.

------------

This wraps too.*
With this.

This wraps too.**With this.

------------

A line break gets put after this line.**
Next line.

A line break gets put after this line.**
Next line.
```

**Comment by tschijnmo** [comment]
@stkb Thank you so much for the addition!  It really rocks and it is added so fast!  I guess it works really great, maybe except a marginal case when a line ends with sentence ending.  For example,
if we have

```
123*5678.
1.
```

and would wrap them to 10 columns, it would become something like

```
123* 5678.**
1.
```

Now if we add something to it as

```
1*123* 5678.**
1.
```

then wrapping it again would give

```
1*123
5678.**
1.
```

rather than

```
1*123* 
5678.**1.
```

It seems that after the double spacing is added and accidentally comes to a line end, it would not be trimmed as insignificant because it has more than 1 space.  Then in all later wrapping, this line will be considered a paragraph ending, and kind of become a barrier to all wrapping over it.

It seems really difficult to differentiate double spaces intentionally added and the double spaces that happened to be put at line ending as a result of wrapping.  Vim and Emacs does not have the feather of using multiple trailing space to signal paragraph ending, so they do not have this problem and just trims all trailing spaces.

Thank you again for such awesome addition!

**Comment by stkb** [comment]
Ah good catch! Thanks for the detailed explanation.

Now I realise that that bug already existed before this feature; it could already happen if there was a double space somewhere in the text.

Thankfully, (unless I've missed something again) it was quite easy to fix. Any deliberate double-space at the end of the line will always end up at the end of a string of wrapped text, so we can leave that, and trim **all** whitespace before the newly-inserted '\n' characters inside the string.

**Comment by tschijnmo** [comment]
@stkb I just has a test and things works like a charm.  Thank you so much for your this extension!
