### ISSUE TITLE
Shortcut conflict

### ISSUE THREAD

**Issue by OliverJAsh** [stkb/vscode-rewrap#20]
The shortcut for rewrapping comments conflicts with VSCode's default `View: Close All Editors` command shortcut.

Since there is already an alternative (`Alt+Q`), can this be removed?

**Comment by stkb** [comment]
Yeah this is tricky. I have no idea how many people are still using the old shortcut, and removing it will "break" the extension for all of them. Then again having the legacy shortcut bothers me too so I might just go ahead and do it.

You can fix it in your own installation though, by adding this to your keybindings.json file:
```
{ 
  "key": "ctrl+k ctrl+w", "command": "-rewrap.rewrapComment" 
}
```
(If you're on mac it'll be `cmd+k cmd+w`)

The `-` in the command removes the keybinding, and the `View: Close All Editors` command will work again for you.

**Comment by OliverJAsh** [comment]
That's really helpful, thank you!
