### ISSUE TITLE
Support rewrap of text in certain HTML tags

### ISSUE THREAD

**Issue by wrummler** [stkb/vscode-rewrap#22]
Rewrap 1.0.0 in VSCode 1.8.0

It'd be nice to support rewrap in HTML-embedded JS/CSS.

So that this:

```
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <script>
        // Support rewrap of JS comments in HTML script tags Support rewrap of JS comments in HTML script tags
    </script>
</head>

<body>
</body>

</html>
```

becomes this:

```
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <script>
        // Support rewrap of JS comments in HTML script tags Support rewrap of
        // JS comments in HTML script tags
    </script>
</head>

<body>
</body>

</html>
```

instead of this currently:

```
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <script>
        // Support rewrap of JS comments in HTML script tags Support rewrap of
        JS comments in HTML script tags
    </script>
</head>

<body>
</body>

</html>
```

**Comment by stkb** [comment]
Hi @wrummler, thanks for the request.

This language-in-a-language scenario gives an interesting challenge and I'd like to do it. I don't think it'll be this side of Christmas though :)

Are there any tags other than <script> you'd like to see supported?

**Comment by wrummler** [comment]
@stkb Probably just script and style elements for JS and CSS respectively. I guess other languages like TS and Less can exist in those elements depending on what environment you've chosen or configured, e.g. [electron-compile](https://github.com/electron/electron-compile). Not sure if that might complicate matters. Thanks for this extension :+1:

**Comment by stkb** [comment]
Ok that seems doable. I'll look into it

**Comment by stkb** [comment]
Have added this in v1.1.0! Hope it works as you expect.

![html-wrapping](https://cloud.githubusercontent.com/assets/6125444/22076322/ec0a7ad2-ddaf-11e6-9a7e-4647c946b533.gif)

**Comment by wrummler** [comment]
Got it, and it works! Thanks.
