### ISSUE TITLE
Check if a language has set its own `editor.rulers` setting and honour that instead.

### ISSUE THREAD

**Issue by redactedscribe** [stkb/vscode-rewrap#25]
Rewrap currently checks for the value defined for the `editor.rulers` user setting to use as the default wrapping column, however in VS Code v1.9.0, it is now possible to define that setting on a [per-language basis](https://code.visualstudio.com/updates/v1_9#_language-specific-settings).

Please make Rewrap honour that setting if it exists for the current editor's language.

Thanks.

**Comment by stkb** [comment]
Have just published v1.2.0 which contains this feature! All settings used by rewrap (`rewrap.wrappingColumn`, `editor.rulers`, `editor.wrappingColumn` and `rewrap.doubleSentenceSpacing`) can be put in a language section and they will override the global values.

Although I found a way, it isn't really officially supported by vscode for extensions to use/access these language-specific settings yet. So if you one of rewrap's own settings in such a section you'll see a green squiggly under it in the settings.json file. But it will still work.

Another note, a global `rewrap.wrappingColumn` setting will still override a language-specific `editor.rulers` setting. So make sure you don't still have a `rewrap.wrappingColumn` in your settings.json if you're using rulers to determine the wrapping column instead.

**Comment by redactedscribe** [comment]
The implementation seems to work as expected, thanks!
