### ISSUE TITLE
Feature request: Dynamic entry of rewrap.wrappingColumn value

### ISSUE THREAD

**Issue by Bill-Stewart** [stkb/vscode-rewrap#27]
It would be nice to have a command in the command list (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>) that lets us dynamically enter a new value for the `rewrap.wrappingColumn` setting.

**Comment by stkb** [comment]
Thanks for the feature request. Not sure what your what your exact use case is, but the new language specific settings feature (#25) in the just-published v1.2.0 lets you use different wrapping columns for different languages, which might already cover it.

If that doesn't however, I have in the past thought about adding a second command that lets you do a wrap (once) at a specified value:

<img width="342" alt="1" src="https://cloud.githubusercontent.com/assets/6125444/22801963/446095c0-ef0f-11e6-9ad5-287b16ba5935.png">
<img width="340" alt="2" src="https://cloud.githubusercontent.com/assets/6125444/22801968/46225b50-ef0f-11e6-9473-e4ab4bcabc56.png">

I wouldn't assign a default keybinding to it, but it would be available in the commands list and you'd be able to assign your own keybinding in the normal way.

The value entered would be preserved within a vscode session (though you'd still have to press enter to confirm each time).

**Comment by Bill-Stewart** [comment]
Yes, a separate "rewrap at specific column" command would meet the need quite nicely!

**Comment by stkb** [comment]
Ok the extra command is now in [v1.3.0](https://github.com/stkb/vscode-rewrap/releases/tag/v1.3.0)

**Comment by Bill-Stewart** [comment]
Cool, thanks!
