### ISSUE TITLE
Selection/cursor position after wrapping

### ISSUE THREAD

**Issue by stkb** [stkb/vscode-rewrap#4]
From @natefinch at https://github.com/Microsoft/vscode/issues/2770#issuecomment-208438916

> One oddity is that it seems to leave wrapped text selected if my cursor was in the text that got wrapped, which means I end up overwriting the text if I wrap in the middle of typing.

> So like, if I write "abc 123 456" and my cursor is after the 6, and the wrapping point is between the letters and numbers. When I wrap, all the text that gets moved to the next line (the numbers) will be selected (with my cursor at the end of the selection).

**Comment by stkb** [comment]
@natefinch Sorry it took a little while, but I've just pushed out a new version (0.5.0). I still fully don't understand why vscode does what it does here, but I've created a fix that I think has your case covered. Please give it a try :)

One thing to note, rewrap always trims single spaces off the ends of lines when wrapping, so if you're at the end of a line and the last thing you typed before wrapping was a space, you'll have to type it again.

**Comment by natefinch** [comment]
I updated the extension, but now I'm getting a warning when I try to run it: "No handler found for the command: 'rewrap.rewrapComment'. Ensure there is an activation event defined, if you are an extension."

My keybinding is 

`{"key": "alt+q", "command": "rewrap.rewrapComment"}`

Not sure what's going on beyond that.

**Comment by stkb** [comment]
Damn, I can't repro... except for when I first reinstalled the extension and I did get exactly that error, but after that, the message "Rewrap has installed, restart Visual Studio Code..." came up; so it was just because the extension hadn't finished installing.

If you're still getting the error, steps to try:
* Uninstall & re-install the extension
* Are there any errors/warnings in the dev console? (View -> Toggle Debug Console -> Console tab)
* If it doesn't work with the custom keybinding, does it work with the default keybinding (`ctrl+k ctrl+w`)? Or by searching for it in the command palette?
* If none of that works, what platform are you on and what type of file(s) does it happen on?

**Comment by natefinch** [comment]
I removed it and reinstalled, restarted vscode.
Nothing in the debug console - happens when I use my keybinding, the default, or choose it from the command palette.   Wacky.

I'm on Ubuntu 16.04 Xenial 64 bit.

**Comment by stkb** [comment]
Ok thanks for trying all that.

I tested it myself in an Ubuntu VM and luckily found and could fix the problem, so have now pushed v0.5.1. Hopefully it should be working for you now (have also downloaded & tested the new version myself on Ubuntu 16.04)

**Comment by natefinch** [comment]
Works great now, thanks!

**Comment by stkb** [comment]
Great!
