### ISSUE TITLE
Default keybinding

### ISSUE THREAD

**Issue by stkb** [stkb/vscode-rewrap#5]
I might have messed up here when choosing the `ctrl+k ctrl+w` keybinding. I was trying to choose one that was in-keeping with other vscode bindings but not already used. As it turns out, `ctrl+k ctrl+w` is already used (though not for a super-important action: workbench.files.action.closeAllFiles).

The shortcuts for this function in Sublime, Emacs, Vim all involve the letter Q.

It's not a huge deal as anyone can remap it to any binding they like, but if most people are doing that then maybe there's a better default to be had.

* Copying Sublime's Alt+Q might be the most sensible option but I'm not happy about a possible conflict with a menu item; if not in English, then in some other language.
* Alt+Shift+Q fits with other "formatting"-type commands, like format document (alt+shift+f), but it's difficult to get your fingers around.
* Ctrl+K Ctrl+Q is another option that's currently free, as is Ctrl+Shift+Q

In any case, if I did choose a different default binding, I'd definitely still keep the old one around for at least a while so as not to break it suddenly for anyone.

If anyone has any comments, please add them here.

**Comment by pkazmier** [comment]
I did find the default binding to be a bit odd as I use all the editors you mention frequently. To your point, there is always the letter Q involved. I did bind rewrap to Alt+Q right away, but after reading this issue, I like the symmetry with Format Code, which I didn't even know existed :-) So, with that said, I've now changed the binding to Alt+Shift+Q.

Thanks for writing this awesome extension. Definitely one of my most used functions in any editor going all the way back to Kyle Jones original adaptive fill mode in Emacs!

**Comment by stkb** [comment]
Hi @pkazmier , thanks for your comments.

I think in the next release, I'm going to change the advertised default to Alt+Q. It seems to be the only sensible default, since it's what most people finding this plugin are used to. Anything else and they'll likely just want to change it to Alt+Q anyway.

Glad you're happy with the extension (and thanks for the review btw!) I admit ignorance to this function in other editors before I wrote rewrap. Now I'm going to check out AdaptiveFillMode to see if there's anything I've missed :)

**Comment by stkb** [comment]
Default changed to Alt+Q in v0.6.0
