### ISSUE TITLE
Wrapping behavior broken in vscode 1.1.0

### ISSUE THREAD

**Issue by dpodder** [stkb/vscode-rewrap#6]
This:
> This is a quick test of rewrap after upgrading vscode to v1.1.0.
> This used to work great in 1.0.0, but now, things get really weird after
> triggering the rewrap plugin.

Turns into this:
> This is a quick test of rewrap
> after upgrading vscode to v1.1.0.
> This used to work great in 1.0.0,
> but now, things get really weird
> after triggering the rewrap
> plugin.triggering the rewrap plugin.

Note that this happens even if I set the rewrap.wrappingColumn setting to 80. There's no trailing whitespace anywhere.

**Comment by stkb** [comment]
Confirmed - I'll get on to this right away. Thanks for reporting

**Comment by stkb** [comment]
@dpodder A couple of vscode's APIs changed their behavior slightly in 1.1.0 which caused everything to break. I've published a fix (v0.5.2) and I think everything works again now.

**Comment by dpodder** [comment]
@stkb Awesome, thanks for the quick fix! v0.5.2 works fine for me now.

**Comment by stkb** [comment]
Cool. Thanks for the review btw :)
