### ISSUE TITLE
Miswrapping on bash scripts

### ISSUE THREAD

**Issue by ahmetalpbalkan** [stkb/vscode-rewrap#7]
I have a file that I set language to `Shell Script (bash)`. It has contents:

```sh
#!/bin/bash

# This script exists because custom-script-shim will detach the enable command
# into background and when that happens the custom-script shim will exit,
# causing test container to exit as its entrypoint has exited. So we use this
# to wait indefinitely until enable background process disappears from ps output.

```

when I run rewrap on this comment block I get 

```sh
# This script exists because custom-script-shim will detach the enable command #
into background and when that happens the custom-script shim will exit, #
causing test container to exit as its entrypoint has exited. So we use this # to
wait indefinitely until enable background process disappears from ps output.
```

screenshot:
![image](https://cloud.githubusercontent.com/assets/159209/17191695/000dc76c-5400-11e6-8112-7258d1d9901f.png)

I use vscode version 1.3.1 and rewrap version 0.5.2

**Comment by stkb** [comment]
Sounds like vscode making breaking changes again. I'll put out a fix very soon. Thanks for reporting!

**Comment by stkb** [comment]
Ok it wasn't what I originally thought. Actually I'd already fixed this bug! just not published the commit. Could update to v0.5.3 and give it another try?

**Comment by stkb** [comment]
Closing: I'm pretty sure this is fixed now
